;;; -*- lexical-binding: t -*-

(server-start)

(load "~/.emacs.d/lisp/emacs-lisp.el")
(load "~/.emacs.d/lisp/misc.el")
(load "~/.emacs.d/lisp/pass.el")
(load "~/.emacs.d/lisp/project.el")
(load "~/.emacs.d/lisp/win.el")
(load "~/.emacs.d/lisp/ruby.el")
(load "~/.emacs.d/lisp/c.el")
(load "~/.emacs.d/lisp/org.el")

(defun my/setup-windows ()
  (interactive)
  (my/switch-to-win-config 1)
  (my/rename-current-win-config "bil")
  (find-file "~/src/github.com/Shopify/billing")
  (split-window-right)
  (windmove-right)
  (split-window-below)
  (windmove-down)
  (vterm "*vterm-bil-shell*")
  (set-window-dedicated-p (get-buffer-window) t)
  (my/switch-to-win-config 2)
  (my/rename-current-win-config "shop")
  (find-file "~/src/github.com/Shopify/shopify")
  (split-window-right)
  (windmove-right)
  (split-window-below)
  (windmove-down)
  (vterm "*vterm-shop-shell*")
  (set-window-dedicated-p (get-buffer-window) t)
  (my/switch-to-win-config 3)
  (my/rename-current-win-config "http")
  (find-file "~/dev/queries/create_business.http")
  (my/switch-to-win-config 4)
  (my/rename-current-win-config "org")
  (find-file "~/org/doing.org")
  (my/switch-to-win-config 5)
  (my/rename-current-win-config "logs")
  (find-file "/opt/dev/var/log")
  (my/switch-to-win-config 6)
  (my/rename-current-win-config "el")
  (find-file "~/.emacs.d/init.el")
  (my/switch-to-win-config 9)
  (my/rename-current-win-config "term")
  (find-file "~/src/github.com/Shopify/billing")
  (vterm "*vterm-bil-server*")
  (vterm "*vterm-bil-worker*")
  (find-file "~/src/github.com/Shopify/shopify")
  (vterm "*vterm-shop-server*")
  (vterm "*vterm-shop-worker*")
  (my/switch-to-win-config 1))

(my/setup-windows)
